src/Band/Entity/Application.php
<?php

namespace App\Band\Entity;

use App\Band\Repository\ApplicationRepository;
use App\Festival\Entity\Festival;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

#[ORM\Table(name: 'band_application')]
#[ORM\UniqueConstraint(columns: ['history_id', 'festival_id'])]
#[ORM\Entity(repositoryClass: ApplicationRepository::class)]
class Application {
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\JoinColumn(nullable: false)]
    #[ORM\ManyToOne(targetEntity: ApplicationHistory::class, cascade: ['PERSIST'], inversedBy: 'applications')]
    private ?ApplicationHistory $history = null;

    #[ORM\JoinColumn(nullable: false)]
    #[ORM\ManyToOne(targetEntity: Festival::class, inversedBy: 'bandApplications')]
    private ?Festival $festival = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $contact_name = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $contact_email = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $contact_phone = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $location = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $facebook = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $instagram = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $youtube = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $spotify = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $twitter = null;

    #[ORM\Column(type: 'text')]
    private ?string $application = null;

    #[ORM\Column(type: 'integer')]
    private ?int $members = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $genders = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $fee = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $technician = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $accommodation = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?DateTimeImmutable $applied_at = null;

    #[ORM\JoinTable(name: 'band_application_genre')]
    #[ORM\JoinColumn(name: 'band_application_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\ManyToMany(targetEntity: Genre::class, fetch: 'EAGER')]
    private Collection $genres;

    #[ORM\OneToMany(mappedBy: 'application', targetEntity: ApplicationScore::class, orphanRemoval: true)]
    private Collection $scores;

    #[ORM\OneToMany(mappedBy: 'application', targetEntity: ApplicationFavorite::class, orphanRemoval: true)]
    private Collection $favorites;

    #[ORM\OneToMany(mappedBy: 'application', targetEntity: ApplicationComment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'application', targetEntity: FinalScore::class, orphanRemoval: true)]
    private Collection $finalScores;

    #[Pure] public function __construct() {
        $this->genres = new ArrayCollection();
        $this->scores = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->finalScores = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getHistory(): ?ApplicationHistory {
        return $this->history;
    }

    public function setHistory(?ApplicationHistory $history): self {
        $this->history = $history;

        return $this;
    }

    public function getFestival(): ?Festival {
        return $this->festival;
    }

    public function setFestival(?Festival $festival): self {
        $this->festival = $festival;

        return $this;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getContactName(): ?string {
        return $this->contact_name;
    }

    public function setContactName(string $contact_name): self {
        $this->contact_name = $contact_name;

        return $this;
    }

    public function getContactEmail(): ?string {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): self {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhone(): ?string {
        return $this->contact_phone;
    }

    public function setContactPhone(?string $contact_phone): self {
        $this->contact_phone = $contact_phone;

        return $this;
    }

    public function getLocation(): ?string {
        return $this->location;
    }

    public function setLocation(string $location): self {
        $this->location = $location;

        return $this;
    }

    public function getWebsite(): ?string {
        return $this->website;
    }

    public function setWebsite(?string $website): self {
        $this->website = $website;

        return $this;
    }

    public function getFacebook(): ?string {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self {
        $this->instagram = $instagram;

        return $this;
    }

    public function getTwitter(): ?string {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self {
        $this->twitter = $twitter;

        return $this;
    }

    public function getYoutube(): ?string {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self {
        $this->youtube = $youtube;

        return $this;
    }

    public function getSpotify(): ?string {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self {
        $this->spotify = $spotify;

        return $this;
    }

    public function getApplication(): ?string {
        return $this->application;
    }

    public function setApplication(string $application): self {
        $this->application = $application;

        return $this;
    }

    public function getMembers(): ?int {
        return $this->members;
    }

    public function setMembers(int $members): self {
        $this->members = $members;

        return $this;
    }

    public function getGenders(): ?string {
        return $this->genders;
    }

    public function setGenders(?string $genders): self {
        $this->genders = $genders;

        return $this;
    }

    public function getFee(): ?string {
        return $this->fee;
    }

    public function setFee(?string $fee): self {
        $this->fee = $fee;

        return $this;
    }

    public function getTechnician(): ?bool {
        return $this->technician;
    }

    public function setTechnician(bool $technician): self {
        $this->technician = $technician;

        return $this;
    }

    public function getAccommodation(): ?bool {
        return $this->accommodation;
    }

    public function setAccommodation(bool $accommodation): self {
        $this->accommodation = $accommodation;

        return $this;
    }

    public function getAppliedAt(): ?DateTimeImmutable {
        return $this->applied_at;
    }

    public function setAppliedAt(?DateTimeImmutable $applied_at): self {
        $this->applied_at = $applied_at;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self {
        if ($this->genres->contains($genre)) {
            $this->genres->removeElement($genre);
        }

        return $this;
    }

    /**
     * @return Collection|ApplicationScore[]
     */
    public function getScores(): Collection {
        return $this->scores;
    }

    public function addScore(ApplicationScore $score): self {
        if (!$this->scores->contains($score)) {
            $this->scores[] = $score;
            $score->setApplication($this);
        }

        return $this;
    }

    public function removeScore(ApplicationScore $score): self {
        if ($this->scores->contains($score)) {
            $this->scores->removeElement($score);
            // set the owning side to null (unless already changed)
            if ($score->getApplication() === $this) {
                $score->setApplication(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ApplicationFavorite[]
     */
    public function getFavorites(): Collection {
        return $this->favorites;
    }

    public function addFavorite(ApplicationFavorite $favorite): self {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setApplication($this);
        }

        return $this;
    }

    public function removeFavorite(ApplicationFavorite $favorite): self {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);

src/System/Entity/EmailRecord.php
<?php

namespace App\System\Entity;

use App\Security\Entity\User;
use App\System\Repository\EmailRecordRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmailRecordRepository::class)]
class EmailRecord {
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Email]
    private ?string $fromEmail = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Email]
    private ?string $toEmail = null;

    #[ORM\JoinColumn(nullable: true)]
    #[ORM\ManyToOne(targetEntity: User::class)]
    private ?User $sender = null;

    #[ORM\JoinColumn(nullable: true)]
    #[ORM\ManyToOne(targetEntity: User::class)]
    private ?User $receiver = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?DateTimeImmutable $sent_at = null;

    #[ORM\Column(type: 'text')]
    private ?string $subject = null;

    #[ORM\Column(type: 'text')]
    private ?string $text = null;

    public function getId(): ?int {
        return $this->id;
    }

    public function getFromEmail(): ?string
    {
        return $this->fromEmail;
    }

    public function setFromEmail(?string $fromEmail): self
    {
        $this->fromEmail = $fromEmail;

        return $this;
    }

    public function getToEmail(): ?string
    {
        return $this->toEmail;
    }

    public function setToEmail(?string $toEmail): self
    {
        $this->toEmail = $toEmail;

        return $this;
    }

    public function getSender(): ?User {
        return $this->sender;
    }

    public function setSender(?User $sender): self {
        $this->sender = $sender;

        return $this;
    }

    public function getReceiver(): ?User {
        return $this->receiver;
    }

    public function setReceiver(?User $receiver): self {
        $this->receiver = $receiver;

        return $this;
    }

    public function getSentAt(): ?DateTimeImmutable {
        return $this->sent_at;
    }

    public function setSentAt(DateTimeImmutable $sent_at): self {
        $this->sent_at = $sent_at;

        return $this;
    }

    public function getSubject(): ?string {
        return $this->subject;
    }

    public function setSubject(string $subject): self {
        $this->subject = $subject;

        return $this;
    }

    public function getText(): ?string {
        return $this->text;
    }

    public function setText(string $text): self {
        $this->text = $text;

        return $this;
    }
}

src/Volunteer/Form/DataMapper/ShiftMapper.php
<?php

namespace App\Volunteer\Form\DataMapper;

use App\Volunteer\Entity\Shift;
use App\Volunteer\Entity\ShiftVolunteer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\UnexpectedTypeException;
use Symfony\Component\Form\FormInterface;
use Traversable;

class ShiftMapper implements DataMapperInterface {
    private EntityManagerInterface $doctrine;

    public function __construct(EntityManagerInterface $doctrine) {
        $this->doctrine = $doctrine;
    }

    /**
     * @var FormInterface[]|Traversable $forms
     */
    public function mapDataToForms($data, $forms): void
    {
        if ($data === null)
            return;

        if (!$data instanceof Shift)
            throw new UnexpectedTypeException($data, Shift::class);

        $forms = iterator_to_array($forms);

        $forms['area']->setData($data->getArea());
        $forms['name']->setData($data->getName());
        $forms['day']->setData($data->getDay());
        $forms['start']->setData($data->getStart());
        $forms['end']->setData($data->getEnd());
        $forms['volunteer']->setData($data->getVolunteers()->isEmpty() ? null : $data->getVolunteers()[0]->getVolunteer());
    }

    /**
     * @param Shift $data
     */
    public function mapFormsToData($forms, &$data): void
    {
        $forms = iterator_to_array($forms);

        $data->setName('');
        $data->setArea($forms['area']->getData());
        $data->setName($forms['name']->getData());
        $data->setDay($forms['day']->getData());
        $data->setStart($forms['start']->getData());
        $data->setEnd($forms['end']->getData());
        if ($forms['volunteer']->getData() != null) {
            if ($data->getVolunteers()->isEmpty()) {
                $sv = new ShiftVolunteer();
                $sv->setVolunteer($forms['volunteer']->getData());
                $sv->setShift($data);
                $this->doctrine->persist($sv);
                $data->setVolunteer($sv);
            } else {
                $sv = $data->getVolunteers()[0];
                $sv->setConfirmed(false);
                $sv->setVolunteer($forms['volunteer']->getData());
            }
        } else {
            foreach ($data->getVolunteers() as $sv)
                $data->removeVolunteer($sv);
        }
    }
}

src/Volunteer/Form/EmailForm.php
<?php

namespace App\Volunteer\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class EmailForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('subject', TextType::class, [
                'label' => 'subject',
                'required' => 'true',
                'constraints' => new NotBlank()
            ])
            ->add('text', TextareaType::class, [
                'attr' => ['rows' => 20],
                'required' => 'true',
                'constraints' => new NotBlank()
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'send'
            ]);
    }
}

src/Volunteer/Form/VolunteerNoteForm.php
<?php

namespace App\Volunteer\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class VolunteerNoteForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('text', TextareaType::class, [
                'required' => false
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'save'
            ]);
    }
}

src/Volunteer/Form/VolunteerResetForm.php
<?php

namespace App\Volunteer\Form;

use App\Volunteer\Enum\VolunteerStatus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class VolunteerResetForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'volunteer.reset.accepted' => VolunteerStatus::ACCEPTED,
                    'volunteer.reset.denied' => VolunteerStatus::DENIED,
                    'volunteer.reset.pending' => VolunteerStatus::PENDING,
                ],
                // select accepted status by default
                'data' => [VolunteerStatus::ACCEPTED],
                'multiple' => true,
                'expanded' => true,
                'required' => true,
                'label' => 'volunteer.reset.label'
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'volunteer.reset.submit',
                'attr' => ['class' => 'btn-danger']
            ]);
    }
}

templates/volunteer/staff/__modal-status.html.twig
<div class="modal fade" id="modal-status" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Status ändern</h5>
            </div>
            <div class="modal-body">
                {{ form(form) }}
            </div>
        </div>
    </div>
</div>

templates/volunteer/staff/volunteer.html.twig
{% extends 'base_sidebar.html.twig' %}
{% import 'buttons.html.twig' as buttons %}

{% block title %}{{ volunteer.firstname }} {{ volunteer.surname }}{% endblock %}

{% set sidebar_parent = {
    route: 'app_staff',
    label: volunteer.firstname ~ ' ' ~ volunteer.surname,
} %}

{% macro shiftInfo(shift, volunteer) %}
    {% set sv = volunteer.getShiftVolunteer(shift) %}
    <i class="fas fa-fw {{ sv != null ? 'fa-check text-success' : 'fa-times text-danger' }}"></i> {{ shift.start|date('D d.m') }}
    {% if sv %}
        <span class="text-muted">({{ sv.start|date('H') }}-{{ sv.end|date('H') }} Uhr)</span>
    {% endif %}
{% endmacro %}

{% macro dayInfo(day, volunteer) %}
    <i class="fas fa-fw {{ day in volunteer.days ? 'fa-check text-success' : 'fa-times text-danger' }}"></i> {{ day.date|date('D d.m') }}
{% endmacro %}

{% block body %}
    <div class="row">
        <div class="col-12 col-lg-6 col-xl-4 order-first">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <strong>{{ volunteer.firstname }} {{ volunteer.surname }}</strong>
                    {% include 'volunteer/staff/__status-icon.html.twig' %}
                </div>
                <table class="table mb-0">
                    {% if is_granted('staff.info.personal') %}
                        <tr>
                            <th scope="row" class="border-top-0">E-Mail:</th>
                            <td class="border-top-0">{{ volunteer.user.email }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Telefon:</th>
                            <td>{{ volunteer.phone }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Geschlecht:</th>
                            <td>{{ ('gender.' ~ volunteer.gender)|trans() }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Geburtstag:</th>
                            <td>{{ volunteer.birthday|date('d.m.Y') }} ({{ volunteer.birthday.diff(date()).y }})</td>
                        </tr>
                        <tr>
                            <th scope="row">Essen:</th>
                            <td>{{ ('food.' ~ volunteer.food)|trans() }}</td>
                        </tr>
                        <tr class="text-decoration-line-through">
                            <th scope="row">T-Shirt:</th>
                            <td>{{ volunteer.shirtsize ?? 'Nein' }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Angemeldet am:</th>
                            <td>{{ volunteer.appliedAt|date('d.m.Y H:i') }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">Präferierte Bereiche:</th>
                        <td>
                            {% for pref in volunteer.preferredAreas %}
                                <p class="m-0">{{ pref.preference }}. {{ pref.shiftArea.name }}</p>
                            {% else %}
                                <i>Keine</i>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Schichten pro Tag:</th>
                        <td>{{ volunteer.preferredShifts }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Gruppen zuordnen:</th>
                        <td>
                            {% for group in groups %}
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="volunteer-group" data-volunteer="{{ volunteer.id }}"
                                           data-group="{{ group.id }}" id="type-{{ group.id }}" {% if group in volunteer.groups %} checked {% endif %}
                                            {% if not is_granted('api.volunteergroup') %} disabled {% endif %}>
                                    <label class="form-check-label text-{{ group.color }}" for="type-{{ group.id }}">{{ group.name }}</label>
                                </div>
                            {% endfor %}
                        </td>
                    </tr>
                    {% if is_granted('staff.info.personal') %}
                        <tr>
                            <th scope="row">Vereinsanmeldung:</th>
                            <td>
                                <a class="btn btn-outline-primary" href="{{ path('app_staff_member_form', {volunteer: volunteer.id}) }}">
                                    <i class="fas fa-file-pdf"></i> Download PDF
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-4 mt-2 mt-lg-0 order-1">
            <div class="card">
                <div class="card-header">
                    <strong>Anwesende Tage</strong>
                </div>
                <div class="card-body py-0 px-2">
                    <div class="row py-1">
                        <div class="col-12"><strong>Aufbau:</strong></div>
                        {% for shift in construction %}
                            <div class="col-12 col-sm-6">{{ _self.shiftInfo(shift, volunteer) }}</div>
                        {% endfor %}
                    </div>
                    <div class="row py-1 border-top">
                        <div class="col-12"><strong>Während dem Festival:</strong></div>
                        {% for shift in days %}
                            <div class="col-12 col-sm-6">{{ _self.dayInfo(shift, volunteer) }}</div>
                        {% endfor %}
                    </div>
                    <div class="row py-1 border-top">
                        <div class="col-12"><strong>Abbau:</strong></div>
                        {% for shift in dismantling %}
                            <div class="col-12 col-sm-6">{{ _self.shiftInfo(shift, volunteer) }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-4 mt-2 mt-xl-0 order-2 order-lg-3 order-xl-2">
            <div class="card">
                <div class="card-header">
                    <strong>Eingeteilte Schichten</strong>
                </div>
                <div class="card-body">
                    {% for shift in shifts %}
                        <a class="text-body" href="{{ path('app_shift', {active: shift.area.id}) }}">
                            <strong>{{ shift.day.date|date('D d.m.') }}</strong>
                            <span class="text-muted">{{ shift.start|date('H:i') }}-{{ shift.end|date('H:i') }} Uhr</span>
                            {{ shift.area.name }}
                        </a>
                        <br>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-4 mt-2 order-3 order-lg-2 order-xl-3">
            <div class="card">
                <div class="card-header">
                    <strong>Erfahrung</strong>
                </div>
                <div class="card-body">
                    {{ volunteer.experience }}
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-4 mt-2 order-4">
            <div class="card">
                <div class="card-header">
                    <strong>Mitteilungen</strong>
                </div>
                <div class="card-body">
                    {{ volunteer.comments }}
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-4 mt-2 order-5">
            <div class="card">
                <div class="card-header">
                    <strong>Interne Notizen</strong>
                </div>
                <div class="card-body">
                    {% if is_granted('staff.edit') %}
                        {{ form_start(form_note) }}
                        {{ form_widget(form_note.text) }}
                        <div class="mt-2">
                            {{ form_widget(form_note.submit) }}
                        </div>
                        {{ form_end(form_note) }}
                    {% else %}
                        {{ volunteer.notes | nl2br }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if is_granted('staff.edit') %}
        <div class="row mt-1">
            <div class="col-12 col-md-6 col-lg-3 mt-2">
                <button type="button" class="btn btn-success form-control" data-bs-toggle="modal" data-bs-target="#modal-accept"
                        data-backdrop="static" data-keyboard="false">
                    Anmeldung akzeptieren
                </button>
            </div>
            <div class="col-12 col-md-6 col-lg-3 mt-2">
                <button type="button" class="btn btn-danger form-control" data-bs-toggle="modal" data-bs-target="#modal-deny"
                        data-backdrop="static" data-keyboard="false">
                    Anmeldung ablehnen
                </button>
            </div>
            <div class="col-12 col-md-6 col-lg-3 mt-2">
                <button type="button" class="btn btn-info form-control" data-bs-toggle="modal" data-bs-target="#modal-email"
                        data-backdrop="static" data-keyboard="false">
                    E-Mail schreiben
                </button>
            </div>
            <div class="col-12 col-md-6 col-lg-3 mt-2">
                <button type="button" class="btn btn-secondary form-control" data-bs-toggle="modal" data-bs-target="#modal-status">
                    Status ändern
                </button>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <strong>E-Mail Historie</strong>&nbsp;&nbsp;&nbsp;<i>Wichtig: Hier werden nur E-Mails angezeigt, die durch dieses
                            Tool verschickt wurden!</i>
                    </div>
                    <table class="table table-sm mb-0">
                        {% for email in emailrecords %}
                            <tr>
                                <th scope="row" class="{{ loop.first ? 'border-top-0' }}">Gesendet am:</th>
                                <td class="{{ loop.first ? 'border-top-0' }}">{{ email.sentAt|date('d.m.Y H:i') }} Uhr</td>
                            </tr>
                            <tr>
                                <th scope="row">Gesendet von:</th>
                                <td>{{ email.sender.name ?? email.sender.email }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Betreff:</th>
                                <td>{{ email.subject }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Inhalt:</th>
                                <td>
                                    {{ email.text|markdown_to_html }}
                                </td>
                            </tr>
                            {% if not loop.last %}
                                <tr>
                                    <td colspan="2" class="bg-light"></td>
                                </tr>
                            {% endif %}
                        {% else %}
                            <tr>
                                <i>Keine E-Mails verschickt</i>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    {% endif %}

    {% include 'volunteer/staff/__modal-email.html.twig' with {
        'id': 'modal-accept',
        'title': 'Anmeldung von ' ~ volunteer.firstname ~ ' annehmen',
        'submit': 'Anmeldung annehmen',
        'submit_class': 'btn-success',
        'to': volunteer.user.email,
        'volunteer': volunteer,
        'form': form_accept,
        'template': template_accept
    } %}

    {% include 'volunteer/staff/__modal-email.html.twig' with {
        'id': 'modal-deny',
        'title': 'Anmeldung von ' ~ volunteer.firstname ~ ' ablehnen',
        'submit': 'Anmeldung ablehnen',
        'submit_class': 'btn-danger',
        'to': volunteer.user.email,
        'volunteer': volunteer,
        'form': form_deny,
        'template': template_deny
    } %}

    {% include 'volunteer/staff/__modal-email.html.twig' with {
        'id': 'modal-email',
        'title': 'Email an ' ~ volunteer.firstname ~ ' senden',
        'submit': 'E-Mail Senden',
        'submit_class': 'btn-primary',
        'to': volunteer.user.email,
        'volunteer': volunteer,
        'form': form_email,
        'template': template_email
    } %}

    {% include 'volunteer/staff/__modal-status.html.twig' with {
        'form': form_status,
    } %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('staff/volunteer') }}
{% endblock %}