src/Volunteer/Form/DataMapper/ShiftMapper.php
<?php

namespace App\Volunteer\Form\DataMapper;

use App\Volunteer\Entity\Shift;
use App\Volunteer\Entity\ShiftVolunteer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\UnexpectedTypeException;
use Symfony\Component\Form\FormInterface;
use Traversable;

class ShiftMapper implements DataMapperInterface {
    private EntityManagerInterface $doctrine;

    public function __construct(EntityManagerInterface $doctrine) {
        $this->doctrine = $doctrine;
    }

    /**
     * @var FormInterface[]|Traversable $forms
     */
    public function mapDataToForms($data, $forms): void
    {
        if ($data === null)
            return;

        if (!$data instanceof Shift)
            throw new UnexpectedTypeException($data, Shift::class);

        $forms = iterator_to_array($forms);

        $forms['area']->setData($data->getArea());
        $forms['name']->setData($data->getName());
        $forms['day']->setData($data->getDay());
        $forms['start']->setData($data->getStart());
        $forms['end']->setData($data->getEnd());
        $forms['volunteer']->setData($data->getVolunteers()->isEmpty() ? null : $data->getVolunteers()[0]->getVolunteer());
    }

    /**
     * @param Shift $data
     */
    public function mapFormsToData($forms, &$data): void
    {
        $forms = iterator_to_array($forms);

        $data->setName('');
        $data->setArea($forms['area']->getData());
        $data->setName($forms['name']->getData());
        $data->setDay($forms['day']->getData());
        $data->setStart($forms['start']->getData());
        $data->setEnd($forms['end']->getData());
        if ($forms['volunteer']->getData() != null) {
            if ($data->getVolunteers()->isEmpty()) {
                $sv = new ShiftVolunteer();
                $sv->setVolunteer($forms['volunteer']->getData());
                $sv->setShift($data);
                $this->doctrine->persist($sv);
                $data->setVolunteer($sv);
            } else {
                $sv = $data->getVolunteers()[0];
                $sv->setConfirmed(false);
                $sv->setVolunteer($forms['volunteer']->getData());
            }
        } else {
            foreach ($data->getVolunteers() as $sv)
                $data->removeVolunteer($sv);
        }
    }
}

src/Volunteer/Form/EmailForm.php
<?php

namespace App\Volunteer\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class EmailForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('subject', TextType::class, [
                'label' => 'subject',
                'required' => 'true',
                'constraints' => new NotBlank()
            ])
            ->add('text', TextareaType::class, [
                'attr' => ['rows' => 20],
                'required' => 'true',
                'constraints' => new NotBlank()
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'send'
            ]);
    }
}

src/Volunteer/Form/ShiftAreaType.php
<?php

namespace App\Volunteer\Form;

use App\System\Application\ConfigService;
use App\Volunteer\Repository\ShiftRepository;
use App\Volunteer\Validator\Constraints\ShiftTimes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Festival\Entity\Festival;

class ShiftAreaType extends AbstractType {
    private ShiftRepository $shiftRepository;
    private ConfigService $config;

    public function __construct(ShiftRepository $shiftRepository, ConfigService $config) {
        $this->shiftRepository = $shiftRepository;
        $this->config = $config;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $shifts = $this->shiftRepository->findAllWhereAreaNameAndFestival($options['area'], $options['festival']);

        $builder->setAttribute('shifts', $shifts);
        foreach ($shifts as $shift) {
            $builder->add($shift->getId(), ShiftType::class, [
                'shift' => $shift,
                'flexible' => $options['flexible'],
                'constraints' => new ShiftTimes([
                    'shift' => $shift
                ]),
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefined([
            'area',
            'flexible',
            'festival'
        ]);
        $resolver->setAllowedTypes('area', 'string');
        $resolver->setAllowedTypes('flexible', 'bool');
        $resolver->setAllowedTypes('festival', Festival::class);
        $resolver->setRequired('area');
        $resolver->setDefaults([
            'flexible' => false,
            'festival' => $this->config->getCurrentFestival()
        ]);
    }

    public function getParent(): string {
        return FormType::class;
    }
}

src/Volunteer/Form/ShiftType.php
<?php

namespace App\Volunteer\Form;

use App\Volunteer\Entity\Shift;
use IntlDateFormatter;
use Locale;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShiftType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $formatter = new IntlDateFormatter(Locale::getDefault(), IntlDateFormatter::FULL, IntlDateFormatter::NONE);
        /** @var Shift $shift */
        $shift = $options['shift'];
        if ($options['flexible']) {
            $builder
                ->add('date', CheckboxType::class, [
                    'label' => $formatter->format($shift->getStart())
                ])
                ->add('start', TimeType::class, [
                    'hours' => range($shift->getStart()->format('H'), $shift->getEnd()->format('H') - 1),
                    'with_minutes' => false,
                    'input' => 'datetime_immutable',
                ])
                ->add('end', TimeType::class, [
                    'hours' => array_reverse(range((int)$shift->getStart()->format('H') + 1, $shift->getEnd()->format('H'))),
                    'with_minutes' => false,
                    'input' => 'datetime_immutable',
                ]);
        } else {
            $builder->add('date', CheckboxType::class, [
                'label' => $shift->getStart()->format('D, d.m. H:i') . ' - ' . $shift->getEnd()->format('H:i')
            ]);
        }
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['shift'] = $options['shift'];
        $view->vars['flexible'] = $options['flexible'];
        $view->vars['data'] = $form->getData();
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefined([
            'shift',
            'flexible'
        ]);
        $resolver->setAllowedTypes('shift', Shift::class);
        $resolver->setAllowedTypes('flexible', 'bool');
        $resolver->setRequired('shift');
        $resolver->setDefaults([
            'flexible' => false,
            'error_mapping' => [
                '.' => 'date'
            ]
        ]);
    }

    public function getParent(): string {
        return FormType::class;
    }
}

src/Volunteer/Form/VolunteerNoteForm.php
<?php

namespace App\Volunteer\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class VolunteerNoteForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('text', TextareaType::class, [
                'required' => false
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'save'
            ]);
    }
}

src/Volunteer/Form/VolunteerResetForm.php
<?php

namespace App\Volunteer\Form;

use App\Volunteer\Enum\VolunteerStatus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class VolunteerResetForm extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'volunteer.reset.accepted' => VolunteerStatus::ACCEPTED,
                    'volunteer.reset.denied' => VolunteerStatus::DENIED,
                    'volunteer.reset.pending' => VolunteerStatus::PENDING,
                ],
                // select accepted status by default
                'data' => [VolunteerStatus::ACCEPTED],
                'multiple' => true,
                'expanded' => true,
                'required' => true,
                'label' => 'volunteer.reset.label'
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'volunteer.reset.submit',
                'attr' => ['class' => 'btn-danger']
            ]);
    }
}

src/Volunteer/Controller/ApiController.php
<?php

namespace App\Volunteer\Controller;

use App\LegacyApiController;
use App\Security\Entity\User;
use App\Volunteer\Entity\Shift;
use App\Volunteer\Entity\ShiftVolunteer;
use App\Volunteer\Entity\Volunteer;
use App\Volunteer\Entity\VolunteerGroup;
use App\Volunteer\Repository\ShiftVolunteerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

// TODO: move all routes to dedicated controllers

/**
 * @deprecated Use dedicated controllers to model api routes
 */
class ApiController extends LegacyApiController {

    // VOLUNTEER

    #[Route(path: '/api/volunteergroup', methods: ['POST'])]
    public function postVolunteerGroup(Request $request, EntityManagerInterface $doctrine): \Symfony\Component\HttpFoundation\Response
    {
        if (!$this->isGranted('api.volunteergroup'))
            return $this->responseForbidden();

        $data = $this->resolveBody($request, [
            'volunteer' => 'int',
            'group' => 'int'
        ]);
        if ($data === false)
            return $this->responseBadRequest();

        /** @var Volunteer $volunteer */
        $volunteer = $doctrine->find(Volunteer::class, $data->volunteer);
        if ($volunteer === null)
            return $this->responseBadRequest();
        /** @var VolunteerGroup $group */
        $group = $doctrine->find(VolunteerGroup::class, $data->group);
        if ($group === null)
            return $this->responseBadRequest();

        $volunteer->addGroup($group);
        $doctrine->flush();

        return $this->responseOk();
    }

    #[Route(path: '/api/volunteergroup', methods: ['DELETE'])]
    public function delVolunteerGroup(Request $request, EntityManagerInterface $doctrine): \Symfony\Component\HttpFoundation\Response
    {
        if (!$this->isGranted('api.volunteergroup'))
            return $this->responseForbidden();

        $data = $this->resolveBody($request, [
            'volunteer' => 'int',
            'group' => 'int'
        ]);
        if ($data === false)
            return $this->responseBadRequest();

        /** @var Volunteer $volunteer */
        $volunteer = $doctrine->find(Volunteer::class, $data->volunteer);
        if ($volunteer === null)
            return $this->responseBadRequest();
        /** @var VolunteerGroup $group */
        $group = $doctrine->find(VolunteerGroup::class, $data->group);
        if ($group === null)
            return $this->responseBadRequest();

        $volunteer->removeGroup($group);
        $doctrine->flush();

        return $this->responseOk();
    }

    #[Route(path: '/api/shiftvolunteer/{id<\d+>}')]
    public function getShiftVolunteer($id, EntityManagerInterface $doctrine): \Symfony\Component\HttpFoundation\Response
    {
        /** @var Shift $shift */
        $shift = $doctrine->find(Shift::class, $id);
        if ($shift === null)
            return $this->responseBadRequest();

        if (!$this->isGranted('api.shiftvolunteer', $shift))
            return $this->responseForbidden();

        if ($shift->getVolunteers()->isEmpty())
            return $this->responseOk();
        $volunteer = $shift->getVolunteers()[0]->getVolunteer();
        return $this->responseOk([
            'volunteerId' => $volunteer->getId(),
            'volunteerName' => $volunteer->getFirstname() . ' ' . $volunteer->getSurname(),
            'shifts' => $volunteer->getOtherShifts($shift),
            'conflict' => $volunteer->hasConflictingShift($shift),
        ]);
    }

    #[Route(path: '/api/shiftvolunteer', methods: ['POST'])]
    public function postShiftVolunteer(Request $request, EntityManagerInterface $doctrine): ?\Symfony\Component\HttpFoundation\Response
    {
        $data = $this->resolveBody($request, [
            'shift' => 'int',
            'volunteer' => '?int'
        ]);
        if ($data === false)
            return $this->responseBadRequest();

        /** @var Shift $shift */
        $shift = $doctrine->find(Shift::class, $data->shift);
        if ($shift === null)
            return $this->responseBadRequest();

        if (!$this->isGranted('api.shiftvolunteer', $shift))
            return $this->responseForbidden();

        if ($data->volunteer != null) {
            /** @var Volunteer $volunteer */
            $volunteer = $doctrine->find(Volunteer::class, $data->volunteer);
            if ($volunteer === null)
                return $this->responseBadRequest();
            if (!$shift->getVolunteers()->isEmpty()) {
                $sv = $shift->getVolunteers()[0];
                $sv->setConfirmed(false);
                $sv->setVolunteer($volunteer);
            } else {
                $sv = new ShiftVolunteer();
                $volunteer->addShift($sv);
                $shift->setVolunteer($sv);
                $doctrine->persist($sv);
            }
            $doctrine->flush();

            return $this->responseOk([
                'volunteerId' => $volunteer->getId(),
                'volunteerName' => $volunteer->getFirstname() . ' ' . $volunteer->getSurname(),
                'shifts' => $volunteer->getOtherShifts($shift),
                'conflict' => $volunteer->hasConflictingShift($shift)
            ]);
        } else {
            $shift->removeVolunteers();
            $doctrine->flush();
            return $this->responseOk();
        }
    }

    #[Route(path: '/api/confirmshift', methods: ['POST'])]
    public function postConfirmShift(Request $request, EntityManagerInterface $doctrine): \Symfony\Component\HttpFoundation\Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_REMEMBERED'))
            return $this->responseForbidden();

        $data = $this->resolveBody($request, [
            'shift' => 'int'
        ]);
        if ($data === false)
            return $this->responseBadRequest();

        /** @var Shift $shift */
        $shift = $doctrine->find(Shift::class, $data->shift);
        if ($shift == null)
            return $this->responseBadRequest();

        /** @var User $user */
        $user = $this->getUser();
        $vol = $user->getVolunteer();
        if ($vol == null)
            return $this->responseForbidden();

        /** @var ShiftVolunteerRepository $repo */
        $repo = $doctrine->getRepository(ShiftVolunteer::class);
        $sv = $repo->findBy([
            'shift' => $shift,
            'volunteer' => $vol->getId()
        ]);
        if (empty($sv))
            return $this->responseBadRequest();
        $sv[0]->setConfirmed(true);
        $doctrine->flush();

        return $this->responseOk();
    }

    // BAND CHECKIN

    #[Route(path: '/api/bandmemberarrived', methods: ['POST'])]
    public function postBandMemberArrived(Request $request, EntityManagerInterface $doctrine): \Symfony\Component\HttpFoundation\Response
    {
        if (!$this->isGranted('checkin.info'))
            return $this->responseForbidden();

        $data = $this->resolveBody($request, [
            'member' => 'int',
            'arrived' => 'bool'
        ]);
        if ($data === false)
            return $this->responseBadRequest();

        $member = $doctrine->find('\App\Band\Entity\BandMember', $data->member);
        if ($member == null)
            return $this->responseBadRequest();
        $member->setArrived($data->arrived);
        $doctrine->flush();

        return $this->responseOk([
            'all' => $member->getTravelParty()->allArrived(),
            'tp' => $member->getTravelParty()->getId()
        ]);
    }
}

templates/volunteer/shift/construction.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Aufbau{% endblock %}

{% block stylesheets %}
    {{ vite_entry_link_tags('theme_shift') }}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                {% for area in areas %}
                    <li class="nav-item">
                        <a href="{{ path(area.name == 'Aufbau' ? 'app_shift_construction' : 'app_shift_dismantling') }}"
                           class="nav-link {{ active == area.id ? 'active' }}">
                            {{ area.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            <div class="shift-table">
                {% for day in days %}
                    <div class="shift-table-time" style="grid-column-start: {{ loop.index }}; grid-row-start: 1">
                        {{ day.shift.name }} {{ day.shift.start|date('d.m.') }}
                        <span class="badge rounded-pill bg-dark float-end mt-1 me-2">{{ day.count }}</span>
                    </div>
                    {% set i = 0 %}
                    {% for hour, volunteers in day.volunteers %}
                        {% set i = i + volunteers.coming|length - volunteers.going|length %}
                        <div class="shift-table-construction"
                             style="grid-column-start: {{ loop.parent.loop.index }}; grid-row-start: {{ loop.index + 1 }}">
                            <span class="text-muted">{{ hour|format('%02d') }} Uhr</span>
                            <span class="badge rounded-pill bg-info float-end mt-1 me-2">{{ i }}</span>
                            <br>
                            {% if volunteers.coming|length > 0 %}
                                <span class="text-success"
                                      title="{{ volunteers.coming|map(v => "#{v.volunteer.firstname} #{v.volunteer.surname}")|join(', ') }}">
                                    <i class="fas fa-arrow-right"></i> <strong>{{ volunteers.coming|length }}</strong>
                                </span>
                                <br>
                            {% endif %}
                            {% if volunteers.going|length > 0 %}
                                <span class="text-danger"
                                      title="{{ volunteers.going|map(v => "#{v.volunteer.firstname} #{v.volunteer.surname}")|join(', ') }}">
                                    <i class="fas fa-arrow-left"></i> <strong>{{ volunteers.going|length }}</strong>
                                </span>
                                <br>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/volunteer/shift/delete.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Schicht bearbeiten{% endblock %}

{% set sidebar_parent = {
    route: 'app_shift',
    label: 'Schicht löschen',
} %}

{% block body %}
    <div class="card">
        <div class="card-header">
            Schicht löschen
        </div>
        <div class="card-body">
            <div class="modal-body">
                Schicht {{ shift.id }}, {{ shift.day.date|date('l') }} {{ shift.start|date('H:i') }}-{{ shift.end|date('H:i') }} Uhr wirklich löschen?
            </div>
        </div>
        <div class="card-footer">
            {{ form_start(form) }}
            <a href="{{ path('app_shift', {festival: shift.day.festival.id, area: shift.area.id}) }}" class="btn btn-secondary">Abbrechen</a>
            {{ form_widget(form.submit) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/volunteer/shift/edit.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Schicht bearbeiten{% endblock %}

{% set sidebar_parent = {
    route: 'app_shift',
    label: 'Schicht bearbeiten',
} %}

{% block body %}
    <div class="card">
        <div class="card-header">
            Schicht bearbeiten
        </div>
        {{ form_start(form) }}
        <div class="card-body">
            <div class="modal-body">
                {{ form_row(form.area) }}
                {{ form_row(form.name) }}
                {{ form_row(form.day) }}
                {{ form_row(form.start) }}
                {{ form_row(form.end) }}
                {{ form_row(form.volunteer) }}
            </div>
        </div>
        <div class="card-footer">
            <a href="{{ path('app_shift', {festival: shift.day.festival.id, area: shift.area.id}) }}" class="btn btn-secondary">Abbrechen</a>
            {{ form_widget(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>

    <div class="d-none">
        {% for day in days %}
            <div id="festival-day-{{ day.id }}" data-year="{{ day.date|date('Y') }}" data-month="{{ day.date|date('m') }}" data-day="{{ day.date|date('d') }}"></div>
        {% endfor %}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('shift/shift') }}
{% endblock %}

templates/volunteer/shift/index.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Schichtpläne{% endblock %}

{% block stylesheets %}
    {{ vite_entry_link_tags('theme_shift') }}
{% endblock %}

{% macro volunteerSelect(shift, sv) %}
    {% set selected = sv ? sv.volunteer : null %}
    <br/>
    <div class="w-100 {{ is_granted('shift.edit', shift) ? 'shift-table-volunteer' }}" data-shift="{{ shift.id }}"
         data-selected="{{ selected ? selected.id : null }}">
        {% if selected is not null %}
            {{ selected.firstname }} {{ selected.surname }}
            {# TODO: the next two lines create a lot of DB queries. Optimize this #}
            <span class="badge rounded-pill bg-dark">{{ selected.getOtherShifts(shift)|length }}</span>
            {% if selected.hasConflictingShift(shift) %}
                <i class="fas fa-exclamation-triangle text-danger"></i>
            {% endif %}
            {% if sv.confirmed %}
                <i class="fas fa-lock text-success"></i>
            {% endif %}
        {% else %}
            <i>Frei</i>
        {% endif %}
    </div>
{% endmacro %}

{% import _self as self %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                {% for area in areas %}
                    <li class="nav-item">
                        <a href="{{ path('app_shift', {festival: festival.id, area: area.id}) }}" class="nav-link {{ active.id == area.id ? 'active' }}">
                            {{ area.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            {% if is_granted('shift.edit', active) %}
                <button class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#modal-newshift">
                    <i class="fas fa-plus-circle"></i> Neue Schicht
                </button>
            {% endif %}
            <a class="btn btn-outline-info" href="{{ path('app_shift_print', {festival: festival.id, area: active.id}) }}">
                <i class="fas fa-print"></i> Druck
            </a>
            {% for day in shifts %}
                <h6 class="mt-3">{{ day.meta.day }}</h6>
                <div class="shift-table">
                    {% set start = day.meta.start.getTimestamp() / 3600 %}
                    {% set end = day.meta.end.getTimestamp() / 3600 - 1 %}
                    {% for i in start..end %}
                        <div class="shift-table-time"
                             style="grid-column-start: {{ (i - start) * day.meta.size + 1 }}; grid-column-end: span {{ day.meta.size }}; grid-row-start: 1">
                            {{ date(i * 3600)|date('H:i') }}
                        </div>
                    {% endfor %}
                    {% for row in day.rows %}
                        {% set r = loop.index + 1 %}
                        {% for shift in row %}
                            <div class="shift-table-shift" data-shift="{{ shift.id }}"
                                 style="grid-column-start: {{ shift.getGridStart(day.meta.start, day.meta.step) }}; grid-column-end: span {{ shift.getGridSpan(day.meta.step) }}; grid-row-start: {{ r }}">
                                <small class="text-muted">{{ shift.start|date('H:i') }} - {{ shift.end|date('H:i') }} Uhr</small>
                                {% if shift.name is not empty %}
                                    {{ shift.name }}
                                {% endif %}
                                {% if is_granted('shift.edit', shift) %}
                                    <small class="float-end shift-table-buttons">
                                        <a href="{{ path('app_shift_edit', {shift: shift.id}) }}">
                                            <i class="fas fa-pen text-warning me-2"></i></a>
                                        <a href="{{ path('app_shift_delete', {shift: shift.id}) }}">
                                            <i class="fas fa-minus-circle text-danger"></i></a>
                                    </small>
                                {% endif %}
                                {% for sv in shift.volunteers %}
                                    {{ self.volunteerSelect(shift, sv) }}
                                {% else %}
                                    {{ self.volunteerSelect(shift, null) }}
                                {% endfor %}
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        <div class="card-footer">
            <ul class="nav">
                <li class="nav-item"><span class="nav-link disabled">Andere Schichtpläne:</span></li>
                {% for f in other_festivals %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_shift', {festival: f.id, area: active.id}) }}">{{ f.start|date('Y') }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="d-none">
        {% for day in days %}
            <div id="festival-day-{{ day.id }}" data-year="{{ day.date|date('Y') }}" data-month="{{ day.date|date('m') }}"
                 data-day="{{ day.date|date('d') }}"></div>
        {% endfor %}
        <select class="form-control form-control-xs" id="shift-volunteer-select">
            <option value="">--</option>
            {% for vol in volunteers %}
                <option value="{{ vol.id }}">{{ vol.firstname }} {{ vol.surname }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="modal fade" id="modal-newshift" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Neue Schicht erstellen</h5>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                    {{ form_row(form.area) }}
                    {{ form_row(form.name) }}
                    {{ form_row(form.day) }}
                    {{ form_row(form.start) }}
                    {{ form_row(form.end) }}
                    {{ form_row(form.volunteer) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if is_granted('shift.edit', active) %}
        {{ vite_entry_script_tags('shift/shift') }}
    {% endif %}
{% endblock %}

templates/volunteer/shift/print.html.twig
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Schichtpl&auml;ne</title>
    {{ vite_entry_link_tags('theme_shift', {'absolute_url': true}) }}
</head>
<body style="background: none">
<div class="p-3 bg-white">
    {% for id, day in shifts %}
        <h1>Schichtplan {{ area.name }}</h1>
        <h3>{{ (days | filter(d => d.id == id) | first).date | date('l, d.m.Y') }}</h3>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Schicht</th>
                <th scope="col">Helfer</th>
                <th scope="col" style="width: 15%">Gekommen</th>
                <th scope="col" style="width: 15%">Fertig</th>
            </tr>
            </thead>
            <tbody>
            {% for shift in day %}
                <tr>
                    <td>{{ shift.start|date('H:i') }} - {{ shift.end|date('H:i') }}</td>
                    <td>
                        {% for sv in shift.volunteers %}
                            {{ sv.volunteer.firstname }} {{ sv.volunteer.surname }}
                        {% endfor %}
                    </td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if not loop.last %}
            <div style="page-break-after: always"></div>
        {% endif %}
    {% endfor %}
</div>
</body>
</html>