src/Security/Entity/User.php
<?php

namespace App\Security\Entity;

use App\Band\Entity\ApplicationComment;
use App\Band\Entity\ApplicationFavorite;
use App\Band\Entity\ApplicationHistory;
use App\Band\Entity\ApplicationScore;
use App\Band\Entity\FinalScore;
use App\Guestlist\Entity\GuestlistInviter;
use App\Inventory\Entity\Item;
use App\Security\Repository\UserRepository;
use App\Volunteer\Entity\ShiftArea;
use App\Volunteer\Entity\Volunteer;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'email.duplicate')]
class User implements UserInterface, PasswordAuthenticatedUserInterface {
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Email]
    #[Assert\NotBlank]
    private ?string $email = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $name = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: 'string')]
    private string $password;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $activationToken = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?DateTimeImmutable $registeredAt = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?DateTimeImmutable $activationEmailSentAt = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?DateTimeImmutable $activatedAt = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?DateTimeImmutable $lastLogin = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $passwordReset = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?DateTimeImmutable $passwordResetTimeout = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $forceReset = null;

    #[ORM\Column(type: 'string', length: 2)]
    private ?string $lang = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Volunteer::class, cascade: ['persist', 'remove'])]
    private ?Volunteer $volunteer = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: GuestlistInviter::class)]
    private ?GuestlistInviter $guestlistInviter = null;

    #[ORM\OneToMany(mappedBy: 'supervisor', targetEntity: ShiftArea::class)]
    private Collection $supervisingAreas;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PermissionInheritance::class)]
    private Collection $permissionInheritances;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ApplicationHistory::class, orphanRemoval: true)]
    private Collection $bandApplicationHistories;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ApplicationScore::class, orphanRemoval: true)]
    private Collection $bandApplicationScores;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ApplicationFavorite::class, orphanRemoval: true)]
    private Collection $bandApplicationFavorites;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: ApplicationComment::class, orphanRemoval: true)]
    private Collection $bandApplicationComments;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: FinalScore::class, orphanRemoval: true)]
    private Collection $bandFinalScores;

    #[ORM\OneToMany(mappedBy: 'borrowedBy', targetEntity: Item::class)]
    private Collection $inventoryItems;

    public function __construct() {
        $this->supervisingAreas = new ArrayCollection();
        $this->permissionInheritances = new ArrayCollection();
        $this->bandApplicationHistories = new ArrayCollection();
        $this->bandApplicationScores = new ArrayCollection();
        $this->bandApplicationFavorites = new ArrayCollection();
        $this->bandApplicationComments = new ArrayCollection();
        $this->bandFinalScores = new ArrayCollection();
        $this->inventoryItems = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getUserIdentifier(): string {
        return $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string {
        return $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password): self {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials() {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(?string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getDisplayName(): string {
        if ($this->name != null)
            return $this->name;
        return $this->email;
    }

    public function getActivationToken(): ?string {
        return $this->activationToken;
    }

    public function setActivationToken(string $activationToken): self {
        $this->activationToken = $activationToken;

        return $this;
    }

    public function getRegisteredAt(): ?DateTimeImmutable {
        return $this->registeredAt;
    }

    public function setRegisteredAt(DateTimeImmutable $registeredAt): self {
        $this->registeredAt = $registeredAt;

        return $this;
    }

    public function getActivationEmailSentAt(): ?DateTimeImmutable {
        return $this->activationEmailSentAt;
    }

    public function setActivationEmailSentAt(DateTimeImmutable $activationEmailSentAt): self {
        $this->activationEmailSentAt = $activationEmailSentAt;

        return $this;
    }

    public function getActivatedAt(): ?DateTimeImmutable {
        return $this->activatedAt;
    }

    public function setActivatedAt(?DateTimeImmutable $activatedAt): self {
        $this->activatedAt = $activatedAt;

        return $this;
    }

    public function getLastLogin(): ?DateTimeImmutable {
        return $this->lastLogin;
    }

    public function setLastLogin(DateTimeImmutable $lastLogin): self {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getPasswordReset(): ?string {
        return $this->passwordReset;
    }

    public function setPasswordReset(?string $passwordReset): self {
        $this->passwordReset = $passwordReset;

        return $this;
    }

    public function getPasswordResetTimeout(): ?DateTimeImmutable {
        return $this->passwordResetTimeout;
    }

    public function setPasswordResetTimeout(?DateTimeImmutable $passwordResetTimeout): self {
        $this->passwordResetTimeout = $passwordResetTimeout;

        return $this;
    }

    public function getForceReset(): ?bool {
        return $this->forceReset;
    }

    public function setForceReset(bool $forceReset): self {
        $this->forceReset = $forceReset;

        return $this;
    }

    public function getLang(): ?string {
        return $this->lang;
    }

    public function setLang(string $lang): self {
        $this->lang = $lang;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array {
        return ['ROLE_USER'];
    }

    public function getVolunteer(): ?Volunteer {
        return $this->volunteer;
    }

    public function setVolunteer(Volunteer $volunteer): self {
        $this->volunteer = $volunteer;

        // set the owning side of the relation if necessary
        if ($this !== $volunteer->getUser()) {
            $volunteer->setUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|ShiftArea[]
     */
    public function getSupervisingAreas(): Collection {
        return $this->supervisingAreas;
    }

    public function addSupervisingArea(ShiftArea $supervisingArea): self {
        if (!$this->supervisingAreas->contains($supervisingArea)) {
            $this->supervisingAreas[] = $supervisingArea;
            $supervisingArea->setSupervisor($this);
        }

        return $this;
    }

    public function removeSupervisingArea(ShiftArea $supervisingArea): self {
        if ($this->supervisingAreas->contains($supervisingArea)) {
            $this->supervisingAreas->removeElement($supervisingArea);
            // set the owning side to null (unless already changed)
            if ($supervisingArea->getSupervisor() === $this) {
                $supervisingArea->setSupervisor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PermissionInheritance[]
     */
    public function getPermissionInheritances(): Collection {
        return $this->permissionInheritances;
    }

    public function addPermissionInheritance(PermissionInheritance $inheritance): self {
        if (!$this->permissionInheritances->contains($inheritance)) {
            $this->permissionInheritances[] = $inheritance;
            $inheritance->setUser($this);
        }

        return $this;
    }

    public function removePermission(PermissionInheritance $permission): self {
        $this->permissionInheritances->removeElement($permission);

        return $this;
    }

    /**

src/Security/Controller/AccountController.php
<?php

namespace App\Security\Controller;

use App\Security\Entity\User;
use App\Security\Form\AccountForm;
use App\Security\Repository\UserRepository;
use App\System\Application\ConfigService;
use App\System\Application\MailService;
use App\System\Application\TokenGeneratorService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route(path: '/account')]
class AccountController extends AbstractController
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly UserRepository $userRepository,
        private readonly UserPasswordHasherInterface $passwordHasher,
        private readonly TranslatorInterface $translator,
        private readonly TokenGeneratorService $tokenGenerator,
        private readonly MailService $mailService,
    ) {}

    #[Route(path: '/', name: 'app_account')]
    public function account(Request $request): Response
    {
        // force the user to log in if they used remember_me
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        /** @var User $user */
        $user = $this->getUser();
        $oldEmail = $user->getEmail();

        $form = $this->createForm(AccountForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $form->get('password')->getData();
            if (!empty($password)) {
                if ($password === $form->get('passwordConfirm')->getData()) {
                    $this->addFlash('success', $this->translator->trans('password.reset.success'));
                    $user->setPassword($this->passwordHasher->hashPassword($user, $password));
                } else {
                    $form->get('passwordConfirm')->addError(new FormError($this->translator->trans('password.nomatch')));
                }
            }

            if ($oldEmail !== $user->getEmail()) {
                $user->setActivationToken($this->tokenGenerator->generateToken(16));
                $user->setActivatedAt(null);
                $user->setActivationEmailSentAt(new DateTimeImmutable());
                $this->mailService->sendChangeaddressEmail($user);
            }

            $this->entityManager->persist($user);
            $this->entityManager->flush();
        }

        return $this->render('security/account.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/reset', name: 'app_reset')]
    public function reset(Request $request): Response
    {
        $form = $this->createFormBuilder()
            ->add('email', EmailType::class, [
                'label' => 'password.reset.email',
                'invalid_message' => 'email.invalid',
                'required' => true,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'password.reset.label',
            ])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var $user User */
            $user = $this->userRepository->findOneBy([
                'email' => $form->get('email')->getData(),
            ]);
            $this->addFlash('success', $this->translator->trans('password.reset.sent'));
            if ($user !== null) {
                $token = $this->tokenGenerator->generateToken(32);
                $token_hash = password_hash($token, PASSWORD_BCRYPT, array('cost' => ConfigService::PASSWORD_HASH_STRENGTH));
                $user->setPasswordReset($token_hash);
                $user->setPasswordResetTimeout(new DateTimeImmutable('+1 hour'));
                $this->entityManager->persist($user);
                $this->entityManager->flush();

                $this->mailService->sendResetEmail($user, $token);
            }
            return $this->redirectToRoute('index');
        }
        return $this->render('security/reset.html.twig', [
            'form' => $form->createView(),
            'reset' => false,
        ]);

    }

    /**
     * Allows a user to reset their password.
     *
     * @param int $userid user to reset
     * @param string $token token for verification
     */
    #[Route(path: '/reset/{userid}/{token}', name: 'app_reset_new')]
    public function resetNew(int $userid, string $token, Request $request): Response
    {
        /** @var $user User */
        $user = $this->userRepository->find($userid);
        if ($user !== null) {
            if ($user->getPasswordResetTimeout() === null || $user->getPasswordResetTimeout()->diff(new DateTimeImmutable())->invert === 0) {
                $this->addFlash('danger', $this->translator->trans('password.reset.timeout'));
                return $this->redirectToRoute('index');
            }

            if (!password_verify($token, $user->getPasswordReset())) {
                $this->addFlash('danger', $this->translator->trans('password.reset.invalid'));
                return $this->redirectToRoute('index');
            }

            $form = $this->createFormBuilder()
                ->add('password', PasswordType::class, [
                    'label' => 'password.new.label',
                    'invalid_message' => 'password.weak',
                    'constraints' => [
                        new Length([
                            'min' => ConfigService::PASSWORD_MIN_LENGTH,
                            'max' => ConfigService::PASSWORD_MAX_LENGTH,
                        ]),
                    ],
                ])
                ->add('passwordConfirm', PasswordType::class, [
                    'label' => 'password.new.confirm',
                ])
                ->add('submit', SubmitType::class, [
                    'label' => 'send',
                ])
                ->getForm();
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $pwPlain = $form->get('password')->getData();
                $pwConfi = $form->get('passwordConfirm')->getData();

                if ($pwPlain === $pwConfi) {
                    $user->setPassword($this->passwordHasher->hashPassword($user, $pwPlain));
                    $user->setPasswordReset(null);
                    $user->setPasswordResetTimeout(null);
                    $this->entityManager->persist($user);
                    $this->entityManager->flush();
                    $this->addFlash('success', $this->translator->trans('password.reset.success'));
                    return $this->redirectToRoute('app_login');
                }

                $form->get('passwordConfirm')->addError(new FormError($this->translator->trans('password.nomatch')));
            }

            return $this->render('security/reset.html.twig', [
                'form' => $form->createView(),
                'reset' => true,
            ]);
        }

        $this->addFlash('danger', $this->translator->trans('password.reset.invalid'));
        return $this->redirectToRoute('index');
    }
}

templates/security/admin/groups.html.twig
{% extends 'base_admin.html.twig' %}
{% import 'preload.html.twig' as preload %}

{% block title %}Gruppen{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html.twig' with {
        items: [
            {name: 'Admin Bereich', path: 'admin_index'}
        ],
        current: 'Gruppen'
    } %}
{% endblock %}

{% block heading %}Admin Bereich: Gruppen{% endblock %}

{% block body %}
    <p class="fs-3 m-0">Admin Bereich: Gruppen</p>
    <a href="{{ path('admin_users') }}">Benutzer</a>
    <div id="vue-groups"></div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('admin/groups') }}
{% endblock %}

templates/security/admin/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Backstage Admin{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html.twig' with {
        current: 'Admin Bereich'
    } %}
{% endblock %}

{% block heading %}Admin Bereich{% endblock %}

{% block body %}
    <div class="row mt-3">
        Hier kommt mal ein schönes Dashboard hin...
    </div>
{% endblock %}

templates/security/admin/user.html.twig
{% extends 'base_admin.html.twig' %}
{% import 'preload.html.twig' as preload %}

{% block title %}{{ user.displayName }}{% endblock %}

{% block head %}
    {{ preload.fetch('api.usergroups.get', { userId: user.id }) }}
{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html.twig' with {
        items: [
            {name: 'Admin Bereich', path: 'admin_index'},
            {name: 'Benutzer', path: 'admin_users'}
        ],
        current: user.displayName
    } %}
{% endblock %}

{% block heading %}Admin Bereich: {{ user.displayName }}{% endblock %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-8 p-2">
            <div class="card">
                <div class="card-header">
                    <strong>{{ user.name ? user.name : user.email }}</strong>
                    {% if user.id != app.user.id %}
                        <a href="{{ path('index', {'_switch_user': user.email}) }}"><i class="fas fa-user-secret py-1 float-end"></i></a>
                    {% endif %}
                </div>
                <table class="table mb-0">
                    <tr>
                        <th scope="row" class="border-top-0">ID:</th>
                        <td class="border-top-0">{{ user.id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">E-Mail:</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Name:</th>
                        <td>{{ user.name ?? '-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Registriert:</th>
                        <td>{{ user.registeredAt|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Aktiviert:</th>
                        <td>{{ user.activatedAt is null ? 'nein' : user.activatedAt|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Zuletzt aktiv:</th>
                        <td>{{ user.lastLogin|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sprache:</th>
                        <td>{{ user.lang }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-12 col-md-4 p-2" id="vue-inheritances" data-user-id="{{ user.id }}"></div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('admin/users') }}
{% endblock %}

templates/security/admin/users.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Benutzer{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html.twig' with {
        items: [
            {name: 'Admin Bereich', path: 'admin_index'}
        ],
        current: 'Benutzer'
    } %}
{% endblock %}

{% block heading %}Admin Bereich: Benutzer{% endblock %}

{% block body %}
    <div class="card mt-3">
        <div class="card-header">
            {{ form_start(form) }}
            <div class="input-group">
                <span class="my-auto me-2">Alle Nutzer</span>
                {{ form_widget(form.email, {'attr': {'class': 'ms-auto me-2', 'style': 'max-width: 250px; min-width: 180px', 'placeholder': 'email'}}) }}
                {{ form_widget(form.search, {'attr': {'class': 'btn-outline-secondary'}}) }}
            </div>
            {{ form_end(form) }}
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>E-Mail</th>
                        <th>Name</th>
                        <th colspan="2">Aktiviert</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.email }}</td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.activatedAt is not null ? user.activatedAt|date('d.m.Y') : 'Nein' }}</td>
                            <td>
                                <a href="{{ path('admin_user', {'user': user.id}) }}"><i class="fas fa-pen"></i></a>
                                {% if user.id != app.user.id %}
                                    <a href="{{ path('index', {'_switch_user': user.email}) }}"><i class="fas fa-user-secret ms-2"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if pageCount > 1 %}
            <div class="card-footer">
                <nav aria-label="User navigation">
                    <ul class="pagination mb-0">
                        {% if page > 1 %}
                            <li class="page-item">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': page - 1}) }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}
                        {% for i in 1..pageCount %}
                            <li class="page-item {{ i == page ? 'active' }}">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': i}) }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        {% if page < pageCount %}
                            <li class="page-item">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': page + 1}) }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>
{% endblock %}