src/Guestlist/Entity/Guestlist.php
<?php

namespace App\Guestlist\Entity;

use App\Festival\Entity\Festival;
use App\Guestlist\Model\GuestlistDto;
use App\Guestlist\Repository\GuestlistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GuestlistRepository::class)]
#[ORM\UniqueConstraint(fields: ['festival', 'email'])]
class Guestlist implements JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $token = null;

    #[ORM\JoinColumn(nullable: false)]
    #[ORM\ManyToOne(targetEntity: Festival::class)]
    private ?Festival $festival = null;

    #[ORM\OneToMany(mappedBy: 'guestlist', targetEntity: GuestlistDay::class, cascade: ['persist'], fetch: 'EAGER', orphanRemoval: true)]
    private Collection $days;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\JoinColumn(referencedColumnName: 'user_id', nullable: true)]
    #[ORM\ManyToOne(targetEntity: GuestlistInviter::class, inversedBy: 'guestlistEntries')]
    private ?GuestlistInviter $inviter = null;

    #[ORM\Column(type: 'string', length: 255, enumType: GuestlistType::class)]
    #[Assert\NotBlank]
    private ?GuestlistType $type;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private ?bool $camping = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $origin = null;

    #[ORM\Column(type: 'smallint', nullable: true)]
    #[Assert\GreaterThanOrEqual(0)]
    private ?int $plus = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $checkedIn = false;

    #[ORM\Column(type: 'boolean')]
    private ?bool $backstageCheckedIn = false;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private ?string $state = null;

    #[ORM\ManyToMany(targetEntity: TravelParty::class, mappedBy: 'guestlist')]
    private Collection $travelParties;

    public function __construct()
    {
        $this->days = new ArrayCollection();
        $this->travelParties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFestival(): ?Festival
    {
        return $this->festival;
    }

    public function setFestival(?Festival $festival): self
    {
        $this->festival = $festival;

        return $this;
    }

    public function getDays(): ArrayCollection|Collection
    {
        return $this->days;
    }

    public function addDay(GuestlistDay $day): self
    {
        if (!$this->days->contains($day)) {
            $this->days[] = $day;
            $day->setGuestlist($this);
        }

        return $this;
    }

    public function removeDay(GuestlistDay $day): self
    {
        if ($this->days->contains($day)) {
            $this->days->removeElement($day);
            // set the owning side to null (unless already changed)
            if ($day->getGuestlist() === $this) {
                $day->setGuestlist(null);
            }
        }

        return $this;
    }

    /**
     * @param Collection<GuestlistDay> $days
     */
    public function setDays(Collection $days): self
    {
        $this->days = $days;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    public function getEmailAnonymized(): ?string
    {
        if (!$this->email)
            return null;
        return preg_replace('/(.)(.*)@(.*)/', '$1***@$3', $this->email);
    }

    public function getInviter(): ?GuestlistInviter
    {
        return $this->inviter;
    }

    public function setInviter(?GuestlistInviter $inviter): self
    {
        $this->inviter = $inviter;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }


    public function getType(): ?GuestlistType
    {
        return $this->type;
    }

    public function setType(?GuestlistType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCamping(): ?bool
    {
        return $this->camping;
    }

    public function setCamping(?bool $camping): self
    {
        $this->camping = $camping;

        return $this;
    }

    public function getOrigin(): ?string
    {
        return $this->origin;
    }

    public function setOrigin(?string $origin): self
    {
        $this->origin = $origin;

        return $this;
    }

    public function getPlus(): ?int
    {
        return $this->plus;
    }

    public function setPlus(?int $plus): self
    {
        $this->plus = $plus;

        return $this;
    }

    public function getCheckedIn(): ?bool
    {
        return $this->checkedIn;
    }

    public function setCheckedIn(?bool $checkedIn): self
    {
        $this->checkedIn = $checkedIn;

        return $this;
    }

    function getBackstageCheckedIn(): ?bool
    {
        return $this->backstageCheckedIn;
    }

    public function setBackstageCheckedIn(?bool $backstageCheckedIn): self
    {
        $this->backstageCheckedIn = $backstageCheckedIn;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    /**
     * @return Collection|TravelParty[]
     */
    public function getTravelParties(): Collection
    {
        return $this->travelParties;
    }

    public function addTravelParty(TravelParty $party): self
    {
        if (!$this->travelParties->contains($party)) {
            $this->travelParties[] = $party;
            $party->addGuestlist($this);
        }

        return $this;
    }

    public function removeTravelParty(TravelParty $party): self
    {
        if ($this->travelParties->contains($party)) {
            $this->travelParties->removeElement($party);
            // set the owning side to null (unless already changed)
            if ($party->getGuestlist()->contains($this))
                $party->removeGuestlist($this);
        }

        return $this;
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'festivalId' => $this->festival->getId(),
            'name' => $this->name,
            'email' => $this->email,
            'inviterId' => $this->inviter?->getUser()?->getId(),
            'inviterName' => $this->inviter?->getName(),
            'inviterEmail' => $this->inviter?->getUser()?->getEmail(),
            'type' => $this->type,
            'comment' => $this->comment,
            'camping' => $this->camping,
            'origin' => $this->origin,
            'plus' => $this->plus,
            'checkedIn' => $this->checkedIn,
            'backstageCheckedIn' => $this->backstageCheckedIn,
            'state' => $this->state,
            'days' => $this->days->toArray(),
        ];
    }
}

src/Guestlist/Entity/GuestlistType.php
<?php

declare(strict_types=1);

namespace App\Guestlist\Entity;

enum GuestlistType: string
{
    /**
     * Band members, performers
     */
    case Act = 'act';
    /**
     * Volunteers, technicians
     */
    case Crew = 'crew';
    /**
     * Friends of other festivals or clubs
     */
    case Friend = 'friend';
    /**
     * Sponsors
     */
    case Sponsor = 'sponsor';
    /**
     * Local residents
     */
    case Local = 'local';
}

src/Guestlist/Controller/BandCheckinApiController.php
<?php

namespace App\Guestlist\Controller;

use App\Festival\Application\FestivalService;
use App\Festival\Entity\Festival;
use App\Guestlist\Entity\Band;
use App\Guestlist\Entity\TravelParty;
use App\Guestlist\Model\BandDto;
use App\Guestlist\Model\TravelPartyDto;
use App\Guestlist\Repository\BandRepository;
use App\Guestlist\Repository\GuestlistRepository;
use App\Guestlist\Repository\TravelPartyRepository;
use App\System\Application\MercureService;
use DateTimeZone;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/api/bandcheckin')]
class BandCheckinApiController extends AbstractController
{
    public function __construct(
        private readonly FestivalService        $festivalService,
        private readonly MercureService         $mercure,
        private readonly GuestlistRepository    $guestlistRepository,
        private readonly BandRepository         $bandRepository,
        private readonly TravelPartyRepository  $travelPartyRepository,
        private readonly EntityManagerInterface $entityManager,
    ) {}

    #[Route(path: '/bands', methods: ['GET'], format: 'json')]
    public function getBands(): Response
    {
        $this->denyAccessUnlessGranted('checkin.bands');

        $bands = $this->bandRepository->findBy([], ['name' => 'ASC']);

        return $this->json($bands);
    }

    #[Route(path: '/bands', methods: ['POST'], format: 'json')]
    public function postBand(#[MapRequestPayload] BandDto $dto): Response
    {
        $this->denyAccessUnlessGranted('checkin.bands.edit');

        $band = new Band();
        $band->setName($dto->name);
        $band->setLocation($dto->location);
        $band->setContactName($dto->contactName);
        $band->setContactEmail($dto->contactEmail);
        $band->setContactPhone($dto->contactPhone);

        $this->entityManager->persist($band);
        $this->entityManager->flush();

        return $this->json($band);
    }

    #[Route(path: '/bands/edit/{band<\d+>}', methods: ['PUT'], format: 'json')]
    public function putBand(Band $band, #[MapRequestPayload] BandDto $dto): Response
    {
        $this->denyAccessUnlessGranted('checkin.bands.edit');

        $band->setName($dto->name);
        $band->setLocation($dto->location);
        $band->setContactName($dto->contactName);
        $band->setContactEmail($dto->contactEmail);
        $band->setContactPhone($dto->contactPhone);

        $this->entityManager->flush();

        return $this->json($band);
    }

    #[Route(path: '/bands/delete/{band<\d+>}', methods: ['DELETE'], format: 'json')]
    public function deleteBand(Band $band): Response
    {
        $this->denyAccessUnlessGranted('checkin.bands.edit');

        $response = $this->json([
            'id' => $band->getId(),
            'delete' => true,
        ]);

        $this->entityManager->remove($band);
        $this->entityManager->flush();

        return $this->json($response);
    }

    #[Route(path: '/parties/{festival<\d+>}', methods: ['GET'], format: 'json')]
    public function getTravelParties(Festival $festival, Request $request): Response
    {
        $this->denyAccessUnlessGranted('checkin.info');

        $parties = $this->travelPartyRepository->findAllWhereFestival($festival);

        $this->mercure->addDiscovery($request);
        $response = $this->json($parties);
        $this->mercure->finalizeResponse($response);

        return $response;
    }

    #[Route(path: '/parties/{festival<\d+>}', methods: ['POST'], format: 'json')]
    public function postTravelParty(Festival $festival, #[MapRequestPayload] TravelPartyDto $dto): Response
    {
        $this->denyAccessUnlessGranted('checkin.edit');

        $party = $this->validateTravelPartyRequest($dto, $festival);
        $this->entityManager->persist($party);
        $this->entityManager->flush();
        $this->mercure->publish('bandcheckin/parties/' . $party->getDay()->getFestival()->getId(), $party);

        return $this->json($party);
    }

    #[Route(path: '/parties/edit/{party<\d+>}', methods: ['PUT'], format: 'json')]
    public function putTravelParty(TravelParty $party, #[MapRequestPayload] TravelPartyDto $dto): Response
    {
        $this->denyAccessUnlessGranted('checkin.edit');

        $party = $this->validateTravelPartyRequest($dto, $party->getDay()->getFestival(), $party);
        $this->entityManager->flush();
        $this->mercure->publish('bandcheckin/parties/' . $party->getDay()->getFestival()->getId(), $party);

        return $this->json($party);
    }

    #[Route(path: '/parties/delete/{party<\d+>}', methods: ['DELETE'], format: 'json')]
    public function deleteTravelParty(TravelParty $party): Response
    {
        $this->denyAccessUnlessGranted('checkin.edit');


        $response = $this->json([
            'id' => $party->getId(),
            'delete' => true,
        ]);

        $this->entityManager->remove($party);
        $this->entityManager->flush();
        $this->mercure->publish('bandcheckin/parties/' . $party->getDay()->getFestival()->getId(), $response);

        return $this->json($response);
    }

    private function validateTravelPartyRequest(TravelPartyDto $dto, Festival $festival, TravelParty $party = null): TravelParty
    {
        $band = $this->bandRepository->find($dto->bandId);
        if ($band == null)
            throw new BadRequestHttpException('Unknown band');

        $day = $this->festivalService->getFestivalDay($dto->dayId);
        if ($day == null)
            throw new BadRequestHttpException('Unknown day');

        if ($day->getFestival()->getId() !== $festival->getId())
            throw new BadRequestHttpException('Day does not belong to current festival');

        $guestlist = $this->guestlistRepository->findAllWhereIdIn($dto->guestlistIds);
        if (sizeof($guestlist) != sizeof($dto->guestlistIds))
            throw new BadRequestHttpException('Could not find all specified guestlist entries');

        if ($party == null)
            $party = new TravelParty();
        $party->setBand($band);
        $party->setDay($day);
        // Datetime is saved without timezone information, so we need to set it to the default timezone :(
        $party->setStageTime($dto->stageTime->setTimezone(new DateTimeZone(date_default_timezone_get())));
        $party->setVehicle($dto->vehicle);
        $party->setCheckedIn($dto->checkedIn);
        foreach ($party->getGuestlist() as $entry) {
            if (!in_array($entry, $guestlist))
                $party->removeGuestlist($entry);
        }
        foreach ($guestlist as $entry)
            $party->addGuestlist($entry);

        return $party;
    }

    #[Route(path: '/checkin/{party<\d+>}', methods: ['PUT'], format: 'json')]
    public function checkinParty(TravelParty $party): Response
    {
        $this->denyAccessUnlessGranted('checkin.checkin');

        $party->setCheckedIn(true);
        $this->entityManager->flush();
        $this->mercure->publish('bandcheckin/parties/' . $party->getDay()->getFestival()->getId(), $party);

        return $this->json($party);
    }
}

src/Guestlist/Controller/BandCheckinController.php
<?php

namespace App\Guestlist\Controller;

use App\Festival\Entity\Festival;
use App\Festival\Repository\FestivalDayRepository;
use App\System\Application\MercureService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/bandcheckin')]
class BandCheckinController extends AbstractController {
    private FestivalDayRepository $festivalDayRepository;

    public function __construct(FestivalDayRepository $festivalDayRepository) {
        $this->festivalDayRepository = $festivalDayRepository;
    }

    /**
     * Displays all checkins. Content gets loaded via javascript asynchronously.
     * Authorizes mercure subscriptions for live updates.
     */
    #[Route(path: '/{festival<\d+>?}', name: 'app_checkin')]
    public function index(Festival $festival, MercureService $mercure, Request $request): Response {
        $this->denyAccessUnlessGranted('checkin.info');
        $days = $this->festivalDayRepository->findAllDuringFestival($festival);

        $mercure->authorizeSubscription($request, [
            'guestlist/' . $festival->getId(),
            'bandcheckin/parties/' . $festival->getId()
        ]);

        return $this->render('guestlist/checkin.html.twig', [
            'festival' => $festival,
            'days' => $days
        ]);
    }

    #[Route(path: '/bands', name: 'app_checkin_bands')]
    public function bands(): Response {
        $this->denyAccessUnlessGranted('checkin.bands');

        return $this->render('guestlist/bands.html.twig');
    }
}

templates/guestlist/bands.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Backstage Checkin{% endblock %}
{% block body %}
    <div id="vue-bands">
        <BandsTable />
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('guestlist/bands') }}
{% endblock %}

templates/guestlist/checkin.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Backstage Checkin{% endblock %}

{% block body %}
    <div id="vue-checkin">
        <CheckinTable />
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('guestlist/checkin') }}
{% endblock %}

templates/guestlist/index.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Traffic Jam Gästeliste{% endblock %}

{% block body %}
    <div id="vue-guestlist">
        <GuestListTable festivalId="{{ festival.id }}" />
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ vite_entry_script_tags('guestlist/guestlist') }}
{% endblock %}

templates/guestlist/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Traffic Jam Gästeliste{% endblock %}

{% block body %}
    <div class="card mt-3">
        <div class="card-header">
            <strong>Anmeldung Gästeliste</strong>
        </div>
        <div class="card-body">
            <p>
                Hallo und herzlich willkommen beim Anmeldeformular für das {{ festival.name }}! Wir
                freuen uns, dass du Interesse daran hast, Teil dieses legendären Festivals zu sein.
            </p>
            <p>
                Nachdem du dieses Formular abgeschickt hast, wird unser Team deine Anmeldung prüfen.
                Wir bitten um deine Geduld, während wir dein Anliegen so schnell wie möglich bearbeiten.
                Sobald deine Anmeldung überprüft wurde, erhältst du eine Bestätigung per E-Mail mit
                weiteren Informationen zum nächsten Schritt.
            </p>
            <p>
                Bitte beachte, dass wir ein Newcomer Festival sind und uns deshalb um eine kleine Spende
                am Einlass freuen würden. Jeder Beitrag hilft uns, das Event noch besser zu machen und
                talentierten Newcomer-Bands eine Plattform zu bieten.
            </p>
            <p>
                Vielen Dank für dein Interesse und deine Teilnahme! Wir sehen uns auf dem Festival!
            </p>
            <hr>
            {{ form(form, {'method': 'POST'}) }}
        </div>
    </div>
{% endblock %}

templates/guestlist/status.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Gästeliste Status
{% endblock %}

{% block body %}
    <div class="card mt-3">
        <div class="card-header">
            <strong>Anmeldung Gästeliste</strong>
        </div>
        <div class="card-body">
            Hier kannst du den aktuellen Status deiner Gästelistenanmeldung einsehen.
            <table class="table mt-2">
                <tbody>
                <tr>
                    <th scope="row">Name</th>
                    <td>{{ guestlist.name }}</td>
                </tr>
                <tr>
                    <th scope="row">E-Mail</th>
                    <td>{{ guestlist.emailAnonymized }}</td>
                </tr>
                <tr>
                    <th scope="row">Gruppe</th>
                    <td>{{ ('guestlist.register.types.' ~ guestlist.type.value) | trans }}</td>
                </tr>
                <tr>
                    <th scope="row">Herkunft</th>
                    <td>{{ guestlist.origin }}</td>
                </tr>
                <tr>
                    <th scope="row">Tage</th>
                    <td>
                        <ul class="m-0">
                            {% for day in guestlist.days %}
                                <li>{{ day.day.date | format_date('full') }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Camping</th>
                    <td>{{ guestlist.camping ? 'Ja' : 'Nein' }}</td>
                </tr>
                <tr>
                    <th scope="row">Begleitung</th>
                    <td>{{ guestlist.plus == 0 ? '&mdash;' : '+' ~ guestlist.plus }}</td>
                </tr>
                <tr>
                    <th scope="row">Status</th>
                    <td>
                        {% if guestlist.state == 'new' %}
                            Neu
                        {% elseif guestlist.state == 'email_confirmation_pending' %}
                            Bestätigung der E-Mail Adresse ausstehend.
                        {% elseif guestlist.state == 'email_confirmed' %}
                            Deine Anmeldung wird aktuell bearbeitet.
                        {% elseif guestlist.state == 'accepted' %}
                            Deine Anmeldung wurde angenommen, wir freuen uns auf deinen Besuch.
                        {% elseif guestlist.state == 'rejected' %}
                            Deine Anmeldung wurde abgelehnt.
                            Für Rückfragen wende dich bitte an die Person, die dich eingeladen hat.
                        {% else %}
                            {{ guestlist.state }}
                        {% endif %}
                    </td>
                </tr>
                {% if guestlist.state == 'accepted' %}
                    <tr>
                        <th scope="row">Hinweis</th>
                        <td>Wir freuen uns über eine Spende an der Abendkasse.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}